### Forleng frister
# Husk å oppdater datofeltene til ønsket dato.
# NB: tilDato er ikke "tilOgMedDato"!!!
POST http://localhost:12345/internal/admin/forleng-frister-til-og-med-dato
Content-Type: application/json

{
  "tilDato": "YYYY-MM-DD",
  "nyFrist": "YYYY-MM-DD",
  "årsak": "Forlenget av admin",
  "utførtAv": "admin",
  "enforce": true
}

### Tving annullering av refusjon
POST http://localhost:12345/internal/admin/annuller-refusjon-ved-tilskuddsperiode
Content-Type: application/json

{
  "tilskuddsperiodeId": "<TILSKUDDSPERIODE_ID>"
}

### Forleng frist på refusjon
POST http://localhost:12345/internal/admin/forleng-frister
Content-Type: application/json

{
  "refusjonIder": ["<REFUSJON_ID>"],
  "årsak": "Ekstraordinær utsettelse i påvente av nødvendige opplysninger",
  "nyFrist": "YYYY-MM-DD",
  "enforce": false
}

### Fikse kvitteringen (reberegn)
POST http://localhost:12345/internal/admin/reberegn-dry/{id}
Content-Type: application/json

{
  "harFerietrekkForSammeMåned": false,
  "minusBeløp": -3796,
  "ferieTrekk": 0
}

### Resend refusjon-godkjent-melding
# Burde kun brukes i tilfeller hvor en refusjon ble godkjent, men meldingen ble
# ikke publisert på Kafka.
# Et relevant eksempel kan være at appen fikk problemer og restartet nøyaktig etter
# en vellykket godkjenning (databasetransaksjon), men før eventlytteren ble kalt.
POST http://localhost:12345/internal/admin/send-refusjon-godkjent-melding
Content-Type: application/json

{
  "refusjonId": "<REFUSJON_ID"
}
