apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 1500m
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: tiltak-refusjon
            envVarPrefix: DB