apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 1500m
  liveness:
    path: /internal/actuator/health
    initialDelay: 20
  readiness:
    path: /internal/actuator/health
    initialDelay: 20
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-innside
        - application: tiltak-refusjon-utside
    outbound:
      external:
        - host: tt02.altinn.no
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: tiltak-refusjon
            envVarPrefix: DB
  envFrom:
    - secret: tiltak-refusjon-altinn