apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: tiltak-refusjon
          - envVarPrefix: SPRING_DATASOURCE