apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltak-refusjon-api-alert
  namespace: arbeidsgiver
  labels:
    team: team-tiltak
spec:
  groups:
    - name: tiltak-refusjon-api-alert
      rules:
        - alert: InstanceDown
          expr: count(up) == 0
          for: 3m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/F1qMf"
            summary: |-
              tiltak-refusjon-api har ingen podder tilgjengelig
          labels:
            namespace: team-tiltak # required
            severity: critical
        - alert: TILTAK-REFUSJON-API ERROR!
          expr: sum(increase(logback_events_total{app="tiltak-refusjon-api",level="error"}[10m])) > 0
          for: 10s
          annotations:
            consequence: Feil i loggen til refusjon-api
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/F1qMf"
            summary: |-
              tiltak-refusjon-api har logget en feil :mild-panic-intensifies: Sjekk loggene om noe bør gjøres!
          labels:
            namespace: team-tiltak # required
            severity: critical
