apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltak-refusjon-api-alerts
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  groups:
    - name: tiltak-refusjon-api-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="tiltak-refusjon-api"} == 0
          for: 2m
          annotations:
            action: "`kubectl describe pod {{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l {{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            severity: danger
            tiltal_refusjon_api_type: tiltak-refusjon-api
            alert_type: custom
        - alert: TILTAK-REFUSJON-API ERROR LOG!
          expr: sum(increase(logback_events_total{app="tiltak-refusjon-api",level="error"}[10m])) > 0
          for: 10s
          annotations:
            consequence: Error i loggen til refusjon-api
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/F1qMf"
            summary: |-
              tiltak-refusjon-api har logget en Error :gooder: Sjekk loggene om noe bør gjøres!
          labels:
            severity: danger
            tiltal_refusjon_api_type: tiltak-refusjon-api
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tiltak-refusjon-api-testing-alert-config
  namespace: arbeidsgiver
  labels:
    alertmanagerConfig: tiltak-refusjon-api-testing-alert-config
spec:
  receivers:
    - name: tiltak-refusjon-api-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: 'arbeidsgiver-tiltak-alerts-testing'
          iconEmoji: ':alert:'
          username: 'Alert dev-gcp'
          sendResolved: true
          title: |-
            [\{{ .Status | toUpper }}\{{ if eq .Status "firing" }}:\{{ .Alerts.Firing | len }}\{{ end }}] \{{ .CommonLabels.alertname }}
          text: >-
            \{{ range .Alerts }}
            \{{ if or .Annotations.summary .Annotations.message }}
            \{{ or .Annotations.summary .Annotations.message }}
            \{{ println " " }}
            \{{- end }}
            \{{- if .Annotations.consequence }}
            • *consequence*: \{{ .Annotations.consequence }} \{{ println " " }}
            \{{- end }}
            \{{- if .Annotations.action }}
            • *action*: \{{ .Annotations.action }} \{{ println " " }}
            \{{- end }}
            \{{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "tiltak_refusjon_api_type"
        matchType: "="
        value: "tiltak-refusjon-api"
    groupInterval: 10s
    groupWait: 5s
    receiver: tiltak-refusjon-api-receiver
    repeatInterval: 2m