apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: arbeidsgiver
  name: tiltak-refusjon-api-testing-alert
  namespace: arbeidsgiver
  # test alerts, will always trigger
  # used only to experiment with formatting etc
spec:
  groups:
    - name: tiltak-refusjon-api-testing-alert
      rules:
        - alert: test alert will always trigger
          expr: container_memory_working_set_bytes{namespace="arbeidsgiver", container="tiltak-refusjon-api"} > 99
          for: 1m
          annotations:
            consequence: Feil i loggen til refusjon-api
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/F1qMf"
            documentation: "https://prometheus.io/docs/prometheus/latest/querying/basics/"
            summary: |-
              tiltak-refusjon-api har logget en feil :mild-panic-intensifies: Sjekk loggene om noe bør gjøres!
            sla: "no need to respond"
          labels:
            severity: "info"
            special_type_to_use_in_alertmanager_config: myteam-testing
            alert_type: custom
        - alert: TILTAK-REFUSJON-API ERROR!
          expr: sum(increase(logd_messages_total{log_app="tiltak-refusjon-api",log_level="Error"}[10m])) > 0
          for: 10s
          annotations:
            consequence: Feil i loggen til refusjon-api
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/F1qMf"
            summary: |-
              tiltak-refusjon-api har logget en feil :mild-panic-intensifies: Sjekk loggene om noe bør gjøres!
          labels:
            severity: "info"
            special_type_to_use_in_alertmanager_config: myteam-testing
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tiltak-refusjon-api-testing-alert-config
  namespace: arbeidsgiver
  labels:
    alertmanagerConfig: tiltak-refusjon-api-testing-alert-config
spec:
  receivers:
    - name: myteam-testing-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: 'arbeidsgiver-tiltak-alerts-testing'
          iconEmoji: ':error:'
          username: 'Alert refusjon-api'
          sendResolved: true
#          httpConfig:
#            proxyURL: http://webproxy.nais:8088
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: |-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Summary:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
          color: danger
  route:
    groupBy:
      - alertname
    matchers:
      - name: "special_type_to_use_in_alertmanager_config"
        matchType: "="
        value: "myteam-testing"
    groupInterval: 10s
    groupWait: 5s
    receiver: myteam-testing-receiver
    repeatInterval: 2m