apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: myteam
  name: tiltak-refusjon-api-testing-alert
  namespace: arbeidsgiver
  # test alerts, will always trigger
  # used only to experiment with formatting etc
spec:
  groups:
    - name: tiltak-refusjon-api-testing-alert
      rules:
        - alert: test alert will always trigger
          expr: container_memory_working_set_bytes{namespace="myteam", container="myteam-myapp"} > 99
          for: 1m
          annotations:
            consequence: "_*{{ $labels.container }}*_ has a working set of {{ $value }} bytes, there is no consequence"
            action: "no need to do _anything_"
            documentation: "https://prometheus.io/docs/prometheus/latest/querying/basics/"
            summary: "Container _*{{ $labels.container }}*_ has a working set of {{ $value }} bytes."
            sla: "no need to respond"
          labels:
            severity: "info"
            special_type_to_use_in_alertmanager_config: myteam-testing
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tiltak-refusjon-api-testing-alert-config
  namespace: arbeidsgiver
  labels:
    alertmanagerConfig: myteam-testing-slack
spec:
  receivers:
    - name: myteam-testing-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: 'arbeidsgiver-tiltak-alerts-testing'
          iconEmoji: ':test:'
          username: 'Testing Alert'
          sendResolved: true
          httpConfig:
            proxyURL: http://webproxy.nais:8088
          title: 'tittel kommer her'
          text: 'tekst kommer her'
          color: danger
  route:
    groupBy:
      - alertname
    matchers:
      - name: "special_type_to_use_in_alertmanager_config"
        matchType: "="
        value: "myteam-testing"
    groupInterval: 10s
    groupWait: 5s
    receiver: myteam-testing-receiver
    repeatInterval: 2m