apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api-labs
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  env:
    - name: MILJO
      value: dev-gcp-labs
  image: {{image}}
  resources:
    limits:
      cpu: 1500m
  liveness:
    path: /internal/actuator/health
    initialDelay: 20
  readiness:
    path: /internal/actuator/health
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-saksbehandler-labs
        - application: tiltak-refusjon-arbeidsgiver-labs
        - application: tiltaksgjennomforing-api-labs
    outbound:
      rules:
        - application: tiltak-fakelogin
        - application: tiltak-refusjon-api-wiremock
