host:
  - api-gw-q0.oera.no
  - tiltak-proxy.dev-fss-pub.nais.io
  - graph.microsoft.com
  - login.microsoftonline.com
tenant: trygdeetaten.no
slack_alert_channel: arbeidsgiver-notifications-test
env:
  PROXY_CLIENT_ID: a7f34b33-cd4d-4e94-aea8-867ab609ecf5