host:
  - tiltak-proxy.dev-fss-pub.nais.io
  - graph.microsoft.com
  - login.microsoftonline.com
  - team-tiltak-unleash-api.nav.cloud.nais.io
tenant: trygdeetaten.no
besluttergruppe: fbfea82d-13da-43ad-a2f2-d7f21cb95f12
slack_alert_channel: arbeidsgiver-notifications-test
kafka-pool: nav-dev
env:
  PROXY_CLIENT_ID: dev-fss.arbeidsgiver.tiltak-proxy
  MILJO: dev-gcp
db-tier: db-f1-micro
memory-limit: 3000Mi
memory-requests: 1000Mi
unleash-enviroment: development
