apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 1500m
  liveness:
    path: /internal/actuator/health
    initialDelay: 20
  readiness:
    path: /internal/actuator/health
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-innside
        - application: tiltak-refusjon-utside
        - application: tiltaksgjennomforing-api
    outbound:
      rules:
        - application: tiltak-fakelogin
        - application: tiltak-refusjon-api-wiremock
      external:
        - host: tiltak-fakelogin.labs.nais.io