apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  env:
    {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
    {{/each}}
  resources:
    limits:
      cpu: 1500m
  liveness:
    path: /internal/actuator/health
    initialDelay: 20
  readiness:
    path: /internal/actuator/health
    initialDelay: 20
  {{#if labs }}
  replicas:
    min: 1
    max: 1
  {{/if}}
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-innside
        - application: tiltak-refusjon-utside
    outbound:
      {{#if labs}}
      rules:
        - application: tiltak-fakelogin
        - application: tiltak-refusjon-api-wiremock
      {{/if}}
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
  kafka:
    pool: {{kafka-pool}}
  {{#unless labs}}
  envFrom:
    - secret: tiltak-refusjon-altinn
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: tiltak-refusjon
            envVarPrefix: DB
  {{/unless}}
