apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  replicas:
    min: 0
    max: 0
  env:
    {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
    {{/each}}
  resources:
    limits:
      cpu: 1500m
  liveness:
    path: /internal/actuator/health
    initialDelay: 20
  readiness:
    path: /internal/actuator/health
    initialDelay: 20
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-saksbehandler
        - application: tiltak-refusjon-arbeidsgiver
    outbound:
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
      rules:
        - application: altinn-rettigheter-proxy
        - application: tiltak-dokgen
  kafka:
    pool: {{kafka-pool}}
  envFrom:
    - secret: tiltak-refusjon-altinn
    - secret: tiltak-refusjon-varsling
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  tokenx:
    enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: tiltak-refusjon
            envVarPrefix: DB
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  strategy:
    type: Recreate
