host:
  - tiltak-proxy.prod-fss-pub.nais.io
  - sokos-kontoregister.prod-fss-pub.nais.io
  - g.nav.no
  - graph.microsoft.com
  - login.microsoftonline.com
  - team-tiltak-unleash-api.nav.cloud.nais.io
  - pdl-api.prod-fss-pub.nais.io
tenant: nav.no
beslutter-gruppe: 156f4f79-6909-4be1-8045-323f55590898
fortrolig-adresse-gruppe: e98efc34-12d1-401f-b059-f17e62834065
strengt-fortrolig-adresse-gruppe: 2931da41-8b8e-42cd-99c0-04a169ddae40
slack_alert_channel: arbeidsgiver-tiltak-alerts
kafka-pool: nav-prod
env:
  PROXY_CLIENT_ID: prod-fss.arbeidsgiver.tiltak-proxy
  MILJO: prod-gcp
db-tier: db-custom-2-7680
db-high-availability: true
memory-limit: 6000Mi
memory-requests: 4000Mi
unleash-environment: production
