host:
  - tiltak-proxy.prod-fss-pub.nais.io
  - graph.microsoft.com
  - login.microsoftonline.com
tenant: nav.no
slack_alert_channel: arbeidsgiver-tiltak-alerts
kafka-pool: nav-prod
env:
  PROXY_CLIENT_ID: prod-fss.arbeidsgiver.tiltak-proxy
db-tier: db-custom-1-3840
memory-limit: 6000Mi
memory-requests: 4000Mi