apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tiltak-refusjon-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-tiltak
  secretName: tiltak-refusjon-api-unleash-api-token
  environment: {{ unleash-environment }}