tiltak-refusjon:
  inntektskomponenten:
    uri: http://localhost:8090/inntekskomponenten/hentinntektliste
    filter: KontrollArbeidsmarkedstiltakA-inntekt
    consumer-id: tiltak-refusjon-api
    call-id: halo01
  altinn-tilgangstyring:
    uri: https://api-gw-q0.oera.no/ekstern/altinn/api/serviceowner/reportees
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    serviceCode: 4936
    serviceEdition: 1
  abac-tilgangstyring:
    uri: https://wasapp-q0.adeo.no/asm-pdp/authorize
    username: TODO
    password: TODO