tiltak-refusjon:
  altinn-tilgangstyring:
    uri: https://tt02.altinn.no/ekstern/altinn/api/serviceowner/reportees
    proxyUri: https://arbeidsgiver.nais.preprod.local/altinn-rettigheter-proxy/ekstern/altinn/api/serviceowner/reportees
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    serviceCode: 4936
    serviceEdition: 1