tiltak-refusjon:
  inntektskomponenten:
    uri: http://tiltak-refusjon-api-wiremock/inntektskomponenten-ws/rs/api/v1/hentinntektliste
    filter: KontrollArbeidsmarkedstiltakA-inntekt
    consumer-id: tiltak-refusjon-api
  altinn-tilgangstyring:
    uri: http://tiltak-refusjon-api-wiremock/ekstern/altinn/api/serviceowner/reportees
    beOmRettighetBaseUrl: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    serviceCode: 4936
    serviceEdition: 1
  abac-tilgangstyring:
    uri: http://tiltak-refusjon-api-wiremock/asm-pdp/authorize
    username: TODO
    password: TODO