spring:
  application:
    name: tiltak-refusjon-api
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "tiltak-refusjon-api-4"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}"
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 4
  jpa:
    open-in-view: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  sql:
    init:
      platform: postgres

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details : always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator

tiltak-refusjon:
  kafka:
    enabled: true
  kontoregister:
    uri: ''
    consumer-id: tiltak-refusjon-api
  inntektskomponenten:
    fake: false
    uri: ''
    filter: KontrollArbeidsmarkedstiltakA-inntekt
    consumer-id: tiltak-refusjon-api
  altinn-tilgangstyring:
    antall: 500
    altinnApiKey: ${ALTINN_API_KEY}
    apiGwApiKey: ${ALTINN_API_GW_API_KEY}
  dokgen:
    uri: "http://tiltak-dokgen/template/tiltak-refusjon/create-pdf"
