tiltak-refusjon:
  kontoregister:
    uri: https://sokos-kontoregister.prod-fss-pub.nais.io/kontoregister/api/v1/hent-kontonummer-for-organisasjon
    consumer-id: tiltak-refusjon-api
  inntektskomponenten:
    uri: https://tiltak-proxy.prod-fss-pub.nais.io/inntektskomponenten-ws/rs/api/v1/hentinntektliste
    filter: KontrollArbeidsmarkedstiltakA-inntekt
    consumer-id: tiltak-refusjon-api
  altinn-tilgangstyring:
    uri: http://altinn-rettigheter-proxy/altinn-rettigheter-proxy/ekstern/altinn/api/serviceowner/reportees
    beOmRettighetBaseUrl: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/?fragment=be-om-tilgang
    inntektsmeldingServiceCode: 4936
    inntektsmeldingServiceEdition: 1
    adressesperreServiceCode: 5516
    adressesperreServiceEdition: 7
  abac-tilgangstyring:
    uri: https://tiltak-proxy.prod-fss-pub.nais.io/application/asm-pdp/authorize
  poao-tilgang:
    url: http://poao-tilgang.poao
    scope: api://prod-gcp.poao.poao-tilgang/.default
  unleash:
    enabled: true
    api-uri: ${UNLEASH_SERVER_API_URL}/api
    api-token: ${UNLEASH_SERVER_API_TOKEN}
  varsling:
    varsling-klar-cron: "0 0 7 5 * ?"
  ad-grupper:
    beslutter: 156f4f79-6909-4be1-8045-323f55590898
    fortrolig-adresse: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    strengt-fortrolig-adresse: ad7b87a6-9180-467c-affc-20a566b0fec0
  norg:
    uri: https://norg2.prod-fss-pub.nais.io/norg2/api/v1
  pdl-api:
    uri: https://pdl-api.prod-fss-pub.nais.io/graphql

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
  client:
    registration:
      tokenx-altinn:
        token-endpoint-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: /var/run/secrets/nais.io/jwker/TOKEN_X_PRIVATE_JWK
          client-auth-method: private_key_jwt
        token-exchange:
          audience: ${NAIS_CLUSTER_NAME}:arbeidsgiver:altinn-rettigheter-proxy
      sokos-kontoregister:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.okonomi.sokos-kontoregister/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad-anonym:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${PROXY_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      poao-tilgang:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${PROXY_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
