server:
  servlet.context-path: /tiltak-refusjon-api

spring:
  main:
    banner-mode: "off"
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}"
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 4
  jpa:
    open-in-view: false

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    enable.executor: true
  health :
    refresh:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details : always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator
