package no.nav.arbeidsgiver.tiltakrefusjon

open class FeilkodeException(val feilkode: Feilkode) : RuntimeException("Feil inntruffet: $feilkode")

enum class Feilkode {
    TEKNISK_FEIL_EREGOPPSLAG,
    TEKNISK_FEIL_EREGOPPSLAG_FANT_IKKE_BEDRIFT,
    EREG_MANGLER_ADRESSEINFO,
    UGYLDIG_STATUS,
    ETTER_FRIST,
    INGEN_INNTEKTER,
    INGEN_BEDRIFTKONTONUMMER,
    ALTINN,
    HAR_KORREKSJON,
    ER_IKKE_KORREKSJON,
    INGEN_KORREKSJONSGRUNNER,
    INNTEKTER_KUN_FRA_TILTAK_OG_OPPGIR_BELØP,
    SAKSBEHANDLER_SVARER_PÅ_INNTEKTSPØRSMÅL,
    UGYLDIG_FORLENGELSE_AV_FRIST,
    FOR_LANG_FORLENGELSE_AV_FRIST,
    KORREKSJONSBELOP_NEGATIVT,
    KORREKSJONSBELOP_POSITIVT,
    KORREKSJONSBELOP_IKKE_NULL,
    INGEN_BESLUTTER,
    SAMME_SAKSBEHANDLER_OG_BESLUTTER,
    KOSTNADSSTED_MANGLER,
    INNTEKTSLINJE_IKKE_MED_I_GRUNNLAG,
    IKKE_TATT_STILLING_TIL_ALLE_INNTEKTSLINJER,
    REFUSJON_BELOP_NEGATIVT_TALL,
    GODKJENN_TIDLIGERE_REFUSJON_FØRST,
    VARIG_LONNSTILSKUDD_MIDLERTIDIG_AVSKURDD,
    FEIL_BEDRIFT_KID_NUMMER
}
