package no.nav.arbeidsgiver.tiltakrefusjon

open class FeilkodeException(val feilkode: Feilkode) : RuntimeException("Feil inntruffet: $feilkode")

enum class Feilkode {
    UGYLDIG_STATUS,
    INGEN_INNTEKTER,
    INGEN_BEDRIFTKONTONUMMER,
    ALTINN,
    HAR_KORREKSJON,
    INNTEKTER_KUN_FRA_TILTAK_OG_OPPGIR_BELØP,
    UGYLDIG_FORLENGELSE_AV_FRIST,
    FOR_LANG_FORLENGELSE_AV_FRIST,
    KORREKSJONSBELOP_NEGATIVT,
    KORREKSJONSBELOP_POSITIVT,
    KORREKSJONSBELOP_IKKE_NULL,
    INGEN_BESLUTTER,
    KOSTNADSSTED_MANGLER,
    INNTEKTSLINJE_IKKE_MED_I_GRUNNLAG,
    IKKE_TATT_STILLING_TIL_ALLE_INNTEKTSLINJER,
    FEIL_BEDRIFT_KIDNUMMER,
    HAR_ALLERDE_UNNTAK_OM_INNTEKTER_2_MND_FREM,
    HAR_ALLERDE_UNNTAK_OM_INNTEKTER_1_MND_FREM,
    LAST_REFUSJONEN_PÅ_NYTT_REFUSJONSGRUNNLAG_ENDRET,
    FERIETREKK_TRUKKET_FOR_SAMME_MÅNED,
    KORREKSJON_KOSTNADSSTED_ANNET_FYLKE,
    INGEN_BEREGNING,
    SAMTIDIGE_ENDRINGER,
    INGEN_TILGANG,
    IKKE_TILGANG_TIL_DELTAKER_STRENGT_FORTROLIG,
    IKKE_TILGANG_TIL_DELTAKER_FORTROLIG,
    IKKE_TILGANG_TIL_DELTAKER_SKJERMET,
    IKKE_TILGANG_TIL_REFUSJON,
}
