package no.nav.arbeidsgiver.tiltakrefusjon.refusjon

enum class SortingOrder {
    DELTAKER_ASC, DELTAKER_DESC, PERIODE_ASC, PERIODE_DESC, STATUS_ASC, STATUS_DESC, FRISTFORGODKJENNING_ASC, FRISTFORGODKJENNING_DESC,LØPENUMMER_ASC,LØPENUMMER_DESC
}