package no.nav.arbeidsgiver.tiltakrefusjon.refusjon

enum class SortingOrder {
    TILTAKSTYPE_ASC, TILTAKSTYPE_DESC, BEDRIFT_ASC, BEDRIFT_DESC, DELTAKER_ASC, DELTAKER_DESC, PERIODE_ASC, PERIODE_DESC, STATUS_ASC, STATUS_DESC, FRISTFORGODKJENNING_ASC, FRISTFORGODKJENNING_DESC,LØPENUMMER_ASC,LØPENUMMER_DESC
}
