### Forleng frister
# Husk å oppdater datofeltene til ønsket dato.
# NB: tilDato er ikke "tilOgMedDato"!!!
POST http://localhost:8080/internal/admin/forleng-frister-til-og-med-dato
Content-Type: application/json

{
  "tilDato": "2023-06-01",
  "nyFrist": "2023-06-30",
  "årsak": "Forlenget av admin",
  "utførtAv": "admin",
  "enforce": true
}

### Tving annullering av refusjon
POST http://localhost:8080/internal/admin/annuller-refusjon-ved-tilskuddsperiode
Content-Type: application/json

{
  "tilskuddsperiodeId": "XXXXXXXX"
}

### Fikse kvitteringen (reberegn)
POST http://localhost:12345/internal/admin/reberegn-dry/{id}
Content-Type: application/json

{
  "harFerietrekkForSammeMåned": false,
  "minusBeløp": -3796,
  "ferieTrekk": 0
}