create table refusjon
(
    id                        varchar primary key,
    deltaker                  varchar,
    deltaker_fnr              varchar(11),
    veileder                  varchar,
    bedrift                   varchar,
    bedriftnummer             varchar(9),
    fra_dato                  date,
    til_dato                  date,
    stillingsprosent          numeric(4, 1),
    feriedager                numeric(4, 1),
    trekk_feriedager_beløp    numeric(8, 2),
    feriepenger               numeric(8, 2),
    sats_feriepenger          numeric(4, 3),
    sykedager                 integer,
    sykepenger                numeric(8, 2),
    sats_otp                  numeric(4, 3),
    beløp_otp                 numeric(8, 2),
    arbeidsgiveravgift        numeric(8, 2),
    sats_arbeidsgiveravgift   numeric(4, 3),
    månedslønn                numeric(8, 2),
    netto_månedslønn          numeric(8, 2),
    sum_utgifter_arbeidsgiver numeric(8, 2),
    sats_refusjon             numeric(3, 2),
    refusjon_pr_måned         numeric(8, 2),
    opprettet_tidspunkt       timestamp default (now()),
    endret_tidspunkt          timestamp default (now()),
    tiltakstype               varchar,
    status                    varchar
);