alter table refusjon drop column if exists tilskuddsgrunnlag_id;
alter table refusjon drop column if exists inntektsgrunnlag_id;
alter table refusjon drop column if exists beregning_id;
alter table refusjon drop column bedrift_kontonummer;
alter table refusjon drop column innhentet_bedrift_kontonummer_tidspunkt;
alter table refusjon drop column inntekter_kun_fra_tiltaket;
alter table refusjon drop column endret_brutto_lønn;
alter table refusjon drop column korreksjonsnummer;
alter table refusjon drop column korreksjon_av_id;
alter table refusjon drop column korrigeres_av_id;
alter table refusjon drop column godkjent_av_saksbehandler;
drop table refusjon_korreksjonsgrunner;